---
linters-settings:
  misspell:
    locale: US

linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - funlen
    - goconst
    - gosec
    - misspell
    - unconvert
    - prealloc
  disable:
    - errcheck
    - ineffassign

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - dupl
        - funlen
        - unused

linters-settings:
  errorlint:
    # Report non-wrapping error creation using fmt.Errorf
    errorf: false
  gosec:
    excludes:
      # don't check math/rand vs crypto/rand
      - G404
